spring:
  datasource:
    url: jdbc:h2:mem:tripdb
    driverClassName: org.h2.Driver
    username: trip
    password: Secret
    data: classpath:trips.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

#TODO: 5. Add Eureka properties configuration for trip-service
eureka:
  instance:
    prefer-ip-address: true
    status-page-url-path: ${server.servlet.context-path}/actuator/info
    health-check-url-path: ${server.servlet.context-path}/actuator/health
  client:
    service-url:
      defaultZone: http://127.0.0.1:4060/demo/discovery/eureka



feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

hystrix:
  dashboard:
    proxyStreamAllowList: "*"
