spring:
  datasource:
    url: jdbc:h2:mem:passengerdb
    driverClassName: org.h2.Driver
    username: passenger
    password: Secret
    data: classpath:passengers.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
    status-page-url-path: ${server.servlet.context-path}/actuator/info
    health-check-url-path: ${server.servlet.context-path}/actuator/health
  client:
    service-url:
      defaultZone: http://127.0.0.1:4060/demo/discovery/eureka

#TODO: 1.2 Add this properties for configuring actuator metrics and push to git repository
management:
  endpoints:
    web:
      exposure:
        include: "*"
